development: 
  type: pop                             
  server: mail.whyspam.me
  username: postmaster@whyspam.me 
  password: mailphr3ak 
  receiver: MyMailer 
  port: 110
  
  
test:
  type: pop
  server: localhost
  username: username
  password: password
  
production: 
  type: IMAP                             
  server: mail.whyspam.me
  username: postmaster@whyspam.me 
  password: mailphr3ak 
  receiver: MyMailer 
 # port: 110
