#!/usr/bin/env ruby
## sudo god -c ./config/fetcher-daemon.god -D
## script/mailer_daemon_fetcher start

require File.dirname(__FILE__) + '/../config/environment.rb'

class MailerDaemonFetcherDaemon < Daemon::Base
  
  @config = YAML.load_file("#{RAILS_ROOT}/config/mailer_daemon.yml")
  @config = @config[RAILS_ENV].to_options
  @sleep_time = @config.delete(:sleep_time) || 30
  def self.start    
    puts "Starting MailerDaemonFetcherDaemon"
    # Add your own receiver object below
        
    @fetcher = Fetcher.create({:receiver => MyMailer}.merge(@config))
    loop do
      @fetcher.fetch
      sleep(@sleep_time)
    end
  end
  
  def self.stop
    puts "Stopping MailerDaemonFetcherDaemon"
  end
  
end

MailerDaemonFetcherDaemon.daemonize
